OBJS = ast.cmo parser.cmo scanner.cmo gob.cmo

gob : $(OBJS)
	ocamlc -o gob $(OBJS)

scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

.PHONY : clean
clean :
	rm -f gob parser.ml parser.mli scanner.ml *.cmo *.cmi

# Generated by ocamldep *.ml *.mli
ast.cmo :
ast.cmx :
codegen.cmo : ast.cmo
codegen.cmx : ast.cmx
goblan.cmo : scanner.cmo parser.cmi codegen.cmo ast.cmo
goblan.cmx : scanner.cmx parser.cmx codegne.cmx ast.cmx
#goblan.cmo : semant.cmo scanner.cmo parser.cmi codegen.cmo ast.cmo
#goblan.cmx : semant.cmx scanner.cmx parser.cmx codegne.cmx ast.cmx
parser.cmo : ast.cmo parser.cmi
parser.cmx : ast.cmx parser.cmx
scanner.cmo : parser.cmi
scanner.cmx : parser.cmx
#semant.cmo : ast.cmo
#semant.cmx : ast.cmx
parser.cmi : ast.cmo
